### PR TITLE
Install unit files in `/etc/systemd/system`

### PR DESCRIPTION
**Pull request by yzl**
### Description
Install unit files in `/etc/systemd/system`. `systemd` gives this location priority.

### Issues Resolved
[chef-server #572](https://github.com/chef/chef-server/issues/572)

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by yzl** [comment]
cc @tas50

**Comment by stevendanna** [comment]
I'm 👍 on this overall.  One question I have is whether it would be useful for us to remove the old version of the file in /usr/lib if it exists so that for upgrades we don't have a confusing case where we have two on disk.

While some may complain that packages shouldn't install files to `/etc/systemd` since that is for local configuration, I think the situation is unclear for non-distribution packages that the administrator installs by hand, which is the case for our server-side packages.  And this is cleaner than trying to deal with the /usr/lib vs /lib split.

**Comment by yzl** [comment]
@stevendanna I'm happy to defer to the general consensus on removing the unused unit file in `/usr/lib`.  I went back and forth and then decided against it because I thought it would be a piece of code that lingers and never gets removed even when it is likely no longer being used.

**Comment by marcparadise** [comment]
:+1: on the change, but I would like to see the old one removed.  Given the long tail on upgrades, it will be years before it's non-functional.

**Comment by mmzyk** [comment]
@marcparadise @stevendanna I initially was thinking like y'all - we should remove the old one, but how likely are we going to be on a system that we're installing to the new location with systemd and the old location exists? Wouldn't this just be failed installs?

Now that I think about it, this would be RHEL 7, given it doesn't have the compilation option that necessitates this fix for Ubuntu. So given that, it would be nice to clean up the old files in a situation like that, @yzl. It'll make for easier debugging if we don't have misleading files left on the system, should we ever be in the situation we're debugging this. I didn't follow your logic for why you left the files in place though @yzl, so maybe I'm missing understanding.

Overall, +1 and think this is fine to go down and the clean up can always be a separate PR.

**Comment by yzl** [comment]
Thank you @stevendanna @marcparadise @mmzyk -- I will merge this and submit a new PR shortly for the cleanup.

**Pull request merged**
