### PR TITLE
Ensure component_runit_supervisor :delete action does not attempt to run a command that does not exist.

### PR DESCRIPTION
**Pull request by smith**
On sysvinit and systemd we attempt to do a `path/embedded/bin/sv stop`, but in some cases this file does not exist. This makes a guard so that the command is not run if that file does not exist.

Also update Gemfile.lock.

### CODE REVIEW

**Comment by smith** [comment]
Created a branch on chef/chef-manage pointing at this and started http://wilson.ci.chef.co/job/chef-manage-trigger-ad_hoc/51/downstreambuildview/ to try it out.

**Comment by smith** [comment]
The build above worked for me.

**Comment by raskchanky** [comment]
@smith does it matter that Travis failed?  :+1: otherwise

**Comment by smith** [comment]
@raskchanky travis failed because of rubocop. #41 (which also needs reviewed) will fix this.

**Pull request merged**
